import * as tencentcloud from "npm:tencentcloud-sdk-nodejs-sms@4.0.812";

const SmsClient = tencentcloud.sms.v20210111.Client;

Deno.serve(async (req) => {
  // Return an empty response if it's an OPTIONS ping (CORS, etc.)
  if (req.method === 'OPTIONS') {
    return new Response('ok', { status: 200 });
  }

  try {
    const payload = await req.json();

    // Optional: Verify that the webhook actually comes from your Supabase project
    const authHeader = req.headers.get('Authorization');
    const secret = Deno.env.get('SUPABASE_HOOK_SECRET');
    if (secret && authHeader !== `Bearer ${secret}`) {
      throw new Error("Invalid Authorization Header");
    }

    // `user.phone` is the full E.164 number (e.g. +8613812345678)
    // `sms.otp` is the verification code generated by Supabase
    const { user, sms } = payload;
    const phone = user?.phone || payload.phone;
    const otp = sms?.otp || payload.otp;

    if (!phone || !otp) {
      throw new Error('Phone or OTP is missing in the payload.');
    }

    // --- MOCK SMS BYPASS FOR TESTING ---
    // Since SMS approval takes time, we immediately return success.
    // Ensure you configured Supabase Auth to use `777777` or test numbers.
    console.log(`[MOCK MODE] SMS suppressed. Intercepted request to send OTP ${otp} to phone ${phone}.`);
    return new Response(JSON.stringify({ success: true, mock: true }), {
      headers: { "Content-Type": "application/json" },
    });
    // -----------------------------------

    /* REAL TENCENT INTEGRATION (Commented out until approval)
    // Instantiate Tencent Cloud Client
    const client = new SmsClient({
      credential: {
        secretId: Deno.env.get("TENCENT_SECRET_ID") || "",
        secretKey: Deno.env.get("TENCENT_SECRET_KEY") || "",
      },
      region: Deno.env.get("TENCENT_SMS_REGION") || "ap-guangzhou",
      profile: {
        httpProfile: {
          endpoint: "sms.tencentcloudapi.com",
        },
      },
    });

    const smsSdkAppId = Deno.env.get("TENCENT_SMS_APP_ID") || "";
    const signName = Deno.env.get("TENCENT_SMS_SIGN_NAME") || "";
    const templateId = Deno.env.get("TENCENT_SMS_TEMPLATE_ID") || "";

    // Tencent API requires format '+8613812345678' in PhoneNumberSet for international formats
    const params = {
      PhoneNumberSet: [phone],
      SmsSdkAppId: smsSdkAppId,
      SignName: signName,
      TemplateId: templateId,
      TemplateParamSet: [otp], // This gets inserted into the SMS template {1}
    };

    console.log(`Sending OTP to ${phone}`);
    const res = await client.SendSms(params);
    console.log("Tencent SMS Response:", JSON.stringify(res));

    // Handle Tencent specific errors returning 200 HTTP but failed SMS
    if (res.SendStatusSet && res.SendStatusSet[0].Code !== "Ok") {
      throw new Error(`Tencent SMS Error: ${res.SendStatusSet[0].Message}`);
    }

    return new Response(JSON.stringify({ success: true }), {
      headers: { "Content-Type": "application/json" },
    });
    */
  } catch (err: any) {
    console.error("Failed to send SMS:", err.message);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
});
