import { Story, Prompt, User, QuestionTemplate, Order, Project } from './types';

export const CATEGORY_COLORS: Record<string, string> = {
  '童年与成长': 'bg-orange-100 text-orange-700',
  '青春与自我发现': 'bg-blue-100 text-blue-700',
  '职场与社会角色': 'bg-teal-100 text-teal-700',
  '爱、关系与家庭': 'bg-pink-100 text-pink-700',
  '内在自我与精神世界': 'bg-purple-100 text-purple-700',
  '习惯、偏好与生活点滴': 'bg-emerald-100 text-emerald-700',
  '转折点与抉择': 'bg-indigo-100 text-indigo-700',
  '反思、展望与遗憾': 'bg-amber-100 text-amber-700',
  '建议': 'bg-gray-100 text-gray-600',
  '自定义': 'bg-gray-100 text-gray-600',
};

export const getCategoryColor = (category?: string) =>
  CATEGORY_COLORS[category || '自定义'] || 'bg-gray-100 text-gray-600';


export const QUESTION_TEMPLATES: QuestionTemplate[] = [
  // 🟢 第一部分：童年与成长
  { id: 'q1', category: '童年与成长', text: '你出生在那一天、哪个城市？' },
  { id: 'q2', category: '童年与成长', text: '父母为你取名时有什么特殊的含义吗？' },
  { id: 'q3', category: '童年与成长', text: '你小时候最喜欢的玩具是什么？' },
  { id: 'q4', category: '童年与成长', text: '童年住过的房子里，你最喜欢哪个角落？' },
  { id: 'q5', category: '童年与成长', text: '描述一下你小时候卧室的样子。' },
  { id: 'q6', category: '童年与成长', text: '你小时候最好的朋友是谁？你们现在还有联系吗？' },
  { id: 'q7', category: '童年与成长', text: '每天放学后，你通常会做的第一件事是什么？' },
  { id: 'q8', category: '童年与成长', text: '你童年时期最崇拜的超级英雄或偶像是谁？' },
  { id: 'q9', category: '童年与成长', text: '小时候你觉得自己长大后会做什么职业？' },
  { id: 'q10', category: '童年与成长', text: '你印象中父母吵架最凶的一次是因为什么？' },
  { id: 'q11', category: '童年与成长', text: '你的祖父母（爷爷奶奶/外公外婆）给你留下的最深印象是什么？' },
  { id: 'q12', category: '童年与成长', text: '小时候你最害怕的一件事是什么（比如黑夜、某种动物）？' },
  { id: 'q13', category: '童年与成长', text: '你童年时期最喜欢的一本书或一部动画片是什么？' },
  { id: 'q14', category: '童年与成长', text: '你第一次感到“委屈”的经历是什么？' },
  { id: 'q15', category: '童年与成长', text: '描述一次你小时候闯过的祸。' },
  { id: 'q16', category: '童年与成长', text: '你们家有什么特殊的过节传统吗？' },
  { id: 'q17', category: '童年与成长', text: '小时候你最喜欢的食物是妈妈做的哪道菜？' },
  { id: 'q18', category: '童年与成长', text: '你在学校里是属于“听话的孩子”还是“调皮的孩子”？' },
  { id: 'q19', category: '童年与成长', text: '哪位老师对你的成长影响最大？为什么？' },
  { id: 'q20', category: '童年与成长', text: '你小时候受过最严重的伤是什么？' },
  { id: 'q21', category: '童年与成长', text: '描述一个你童年时期经常做的梦。' },
  { id: 'q22', category: '童年与成长', text: '你第一次离开家去远行（或夏令营）是什么时候？' },
  { id: 'q23', category: '童年与成长', text: '你的兄弟姐妹中，你和谁的关系最亲近？' },
  { id: 'q24', category: '童年与成长', text: '小时候你最渴望得到的礼物是什么？' },
  { id: 'q25', category: '童年与成长', text: '你的第一个宠物叫什么名字？它教给了你什么？' },

  // 🟡 第二部分：青春与自我发现
  { id: 'q26', category: '青春与自我发现', text: '你的初恋发生在什么时候？对方是什么样的人？' },
  { id: 'q27', category: '青春与自我发现', text: '青春期时，你和父母关系最紧张的时期是几岁？' },
  { id: 'q28', category: '青春与自我发现', text: '你第一次感到“孤独”是在什么时候？' },
  { id: 'q29', category: '青春与自我发现', text: '你少年时期最喜欢的音乐类型或歌手是谁？' },
  { id: 'q30', category: '青春与自我发现', text: '描述一次你为了合群而做出的妥协。' },
  { id: 'q31', category: '青春与自我发现', text: '你在学生时代最擅长的科目和最差的科目分别是什么？' },
  { id: 'q32', category: '青春与自我发现', text: '那个时候你对“成功”的定义是什么？' },
  { id: 'q33', category: '青春与自我发现', text: '描述你第一次心碎的经历。' },
  { id: 'q34', category: '青春与自我发现', text: '你在大学或高中时期做过最疯狂的一件事是什么？' },
  { id: 'q35', category: '青春与自我发现', text: '哪部电影在青少年时期改变了你的世界观？' },
  { id: 'q36', category: '青春与自我发现', text: '你第一次意识到父母也是“普通人”是在哪一刻？' },
  { id: 'q37', category: '青春与自我发现', text: '那个时期的你，最大的容貌焦虑是什么？' },
  { id: 'q38', category: '青春与自我发现', text: '你参加过的印象最深的社团或集体活动是什么？' },
  { id: 'q39', category: '青春与自我发现', text: '你第一份打工赚钱的经历是做什么？' },
  { id: 'q40', category: '青春与自我发现', text: '描述一个你曾深信不疑，后来却彻底抛弃的观念。' },
  { id: 'q41', category: '青春与自我发现', text: '青春期时，你曾暗恋过谁？' },
  { id: 'q42', category: '青春与自我发现', text: '你人生中第一场真正意义上的冒险是什么？' },
  { id: 'q43', category: '青春与自我发现', text: '描述一次你考试失败或竞争失利的经历。' },
  { id: 'q44', category: '青春与自我发现', text: '当时你最想逃离的地方是哪里？' },
  { id: 'q45', category: '青春与自我发现', text: '谁是你那个阶段的“死对头”或竞争对手？' },
  { id: 'q46', category: '青春与自我发现', text: '你第一次喝醉或尝试禁忌事物的经历。' },
  { id: 'q47', category: '青春与自我发现', text: '当时你对未来最大的担忧是什么？' },
  { id: 'q48', category: '青春与自我发现', text: '你觉得自己哪一点最像父亲？哪一点最像母亲？' },
  { id: 'q49', category: '青春与自我发现', text: '你第一次靠自己的能力买下的贵重物品是什么？' },
  { id: 'q50', category: '青春与自我发现', text: '青春期结束时，你觉得自己变成熟了吗？' },

  // 🔵 第三部分：职场与社会角色
  { id: 'q51', category: '职场与社会角色', text: '你的第一份正式工作是什么？' },
  { id: 'q52', category: '职场与社会角色', text: '你拿到第一笔薪水时是怎么花的？' },
  { id: 'q53', category: '职场与社会角色', text: '描述一位对你职业生涯产生重大影响的领导。' },
  { id: 'q54', category: '职场与社会角色', text: '你在工作中感到最有成就感的一瞬间是什么？' },
  { id: 'q55', category: '职场与社会角色', text: '你经历过最严重的职场危机是什么？' },
  { id: 'q56', category: '职场与社会角色', text: '描述一次你不得不为了工作而放弃原则的时刻。' },
  { id: 'q57', category: '职场与社会角色', text: '你是否曾经想过彻底转行？为什么？' },
  { id: 'q58', category: '职场与社会角色', text: '你是如何平衡工作和私人生活的？' },
  { id: 'q59', category: '职场与社会角色', text: '职场教给你最深刻的一个道理是什么？' },
  { id: 'q60', category: '职场与社会角色', text: '如果现在可以退休，你最想做的事情是什么？' },
  { id: 'q61', category: '职场与社会角色', text: '你在团队中通常扮演什么角色（领导者、执行者、调解者）？' },
  { id: 'q62', category: '职场与社会角色', text: '描述一次你被误解或被排挤的职场经历。' },
  { id: 'q63', category: '职场与社会角色', text: '你对“金钱”的态度在这些年里发生了什么变化？' },
  { id: 'q64', category: '职场与社会角色', text: '你最希望自己在职业生涯中留下的遗产（Legacy）是什么？' },
  { id: 'q65', category: '职场与社会角色', text: '工作中，你最讨厌哪种类型的同事？' },
  { id: 'q66', category: '职场与社会角色', text: '你觉得自己是一个好员工/好老板吗？' },
  { id: 'q67', category: '职场与社会角色', text: '你在职业生涯中犯过最大的错误是什么？' },
  { id: 'q68', category: '职场与社会角色', text: '哪次面试让你印象最深刻？' },
  { id: 'q69', category: '职场与社会角色', text: '你如何应对工作带来的压力？' },
  { id: 'q70', category: '职场与社会角色', text: '职场社交中，你最擅长和最不擅长的分别是什么？' },
  { id: 'q71', category: '职场与社会角色', text: '描述你最忙碌、压力最大的一段日子。' },
  { id: 'q72', category: '职场与社会角色', text: '你是否有过创业的念头？' },
  { id: 'q73', category: '职场与社会角色', text: '你的专业技能对你观察世界的方式有什么影响？' },
  { id: 'q74', category: '职场与社会角色', text: '你觉得职场竞争中，天赋和努力哪个更重要？' },
  { id: 'q75', category: '职场与社会角色', text: '现在的你，还保留着刚入职时的热情吗？' },

  // 🔴 第四部分：爱、关系与家庭
  { id: 'q76', category: '爱、关系与家庭', text: '你是如何遇到现在的伴侣（或人生挚爱）的？' },
  { id: 'q77', category: '爱、关系与家庭', text: '婚姻或长期关系教给你最重要的一课是什么？' },
  { id: 'q78', category: '爱、关系与家庭', text: '描述你和孩子（如果有）第一次见面的感受。' },
  { id: 'q79', category: '爱、关系与家庭', text: '你在一段关系中最看重的品质是什么？' },
  { id: 'q80', category: '爱、关系与家庭', text: '描述一次你为爱做出的重大牺牲。' },
  { id: 'q81', category: '爱、关系与家庭', text: '你和最好的朋友之间，最深层的纽带是什么？' },
  { id: 'q82', category: '爱、关系与家庭', text: '你的父母老去这件事，对你意味着什么？' },
  { id: 'q83', category: '爱、关系与家庭', text: '描述一次你和家人之间的严重冲突及和解过程。' },
  { id: 'q84', category: '爱、关系与家庭', text: '你觉得自己是一个容易相处的人吗？' },
  { id: 'q85', category: '爱、关系与家庭', text: '在感情中，你是倾向于付出还是索取？' },
  { id: 'q86', category: '爱、关系与家庭', text: '哪次离别（分手、永别、搬迁）让你最难以释怀？' },
  { id: 'q87', category: '爱、关系与家庭', text: '你最信任的人是谁？为什么？' },
  { id: 'q88', category: '爱、关系与家庭', text: '描述一次你感到被深深理解的时刻。' },
  { id: 'q89', category: '爱、关系与家庭', text: '你如何处理感情中的背叛或失望？' },
  { id: 'q90', category: '爱、关系与家庭', text: '你认为“家”的定义是什么？' },
  { id: 'q91', category: '爱、关系与家庭', text: '你的朋友圈子在过去十年里发生了什么变化？' },
  { id: 'q92', category: '爱、关系与家庭', text: '描述你理想中的周日生活，是和谁在一起？' },
  { id: 'q93', category: '爱、关系与家庭', text: '你对父母有哪些一直没说出口的感激或遗憾？' },
  { id: 'q94', category: '爱、关系与家庭', text: '你认为最好的育儿方式是什么？' },
  { id: 'q95', category: '爱、关系与家庭', text: '在爱情中，你最不能忍受的行为是什么？' },
  { id: 'q96', category: '爱、关系与家庭', text: '曾为了谁而改变过自己的性格？' },
  { id: 'q97', category: '爱、关系与家庭', text: '描述一个你和朋友或爱人的共同小癖好。' },
  { id: 'q98', category: '爱、关系与家庭', text: '哪段关系让你觉得最具挑战性？' },
  { id: 'q99', category: '爱、关系与家庭', text: '如果你明天就要离开，你想对另一半说的一句话是什么？' },
  { id: 'q100', category: '爱、关系与家庭', text: '你相信“灵魂伴侣”吗？' },

  // 🟣 第五部分：内在自我与精神世界
  { id: 'q101', category: '内在自我与精神世界', text: '你最喜欢自己的哪一个性格特征？' },
  { id: 'q102', category: '内在自我与精神世界', text: '哪一个性格缺点是你最想改正的？' },
  { id: 'q103', category: '内在自我与精神世界', text: '你的座右铭或人生准则是什么？' },
  { id: 'q104', category: '内在自我与精神世界', text: '你相信有死后的世界或轮回吗？' },
  { id: 'q105', category: '内在自我与精神世界', text: '描述一个让你感到最平静的地方（现实中或脑海里）。' },
  { id: 'q106', category: '内在自我与精神世界', text: '哪种情绪是你最难掌控的？' },
  { id: 'q107', category: '内在自我与精神世界', text: '你认为人生最大的快乐来源是什么？' },
  { id: 'q108', category: '内在自我与精神世界', text: '你害怕衰老吗？为什么？' },
  { id: 'q109', category: '内在自我与精神世界', text: '如果余生只能保留一段记忆，你会选哪一段？' },
  { id: 'q110', category: '内在自我与精神世界', text: '描述你对“死亡”的态度。' },
  { id: 'q111', category: '内在自我与精神世界', text: '什么是你愿意为之奋斗终生的信仰或事业？' },
  { id: 'q112', category: '内在自我与精神世界', text: '哪本书或哪位哲学家对你的三观影响最大？' },
  { id: 'q113', category: '内在自我与精神世界', text: '你觉得自己是一个悲观主义者还是乐观主义者？' },
  { id: 'q114', category: '内在自我与精神世界', text: '你的“舒适区”是什么样的？' },
  { id: 'q115', category: '内在自我与精神世界', text: '如果你可以拥有一个超能力，你会选什么？' },
  { id: 'q116', category: '内在自我与精神世界', text: '你最羡慕别人的哪一点？' },
  { id: 'q117', category: '内在自我与精神世界', text: '描述一个你感到自己“格格不入”的时刻。' },
  { id: 'q118', category: '内在自我与精神世界', text: '你的底线在哪里？' },
  { id: 'q119', category: '内在自我与精神世界', text: '哪种赞美最能让你感到开心？' },
  { id: 'q120', category: '内在自我与精神世界', text: '你认为生命是有意义的，还是随机发生的？' },
  { id: 'q121', category: '内在自我与精神世界', text: '独处时，你通常都在想些什么？' },
  { id: 'q122', category: '内在自我与精神世界', text: '你对自己目前的生活状态满意度（1-10分）是多少？' },
  { id: 'q123', category: '内在自我与精神世界', text: '你是否有过什么至今无人知晓的秘密（或隐秘的爱好）？' },
  { id: 'q124', category: '内在自我与精神世界', text: '描述一次你感到“神圣”或超脱现实的体验。' },
  { id: 'q125', category: '内在自我与精神世界', text: '如果能回到过去改变一件事，你会改什么？' },

  // 🟠 第六部分：习惯、偏好与生活点滴
  { id: 'q126', category: '习惯、偏好与生活点滴', text: '你是个早起的人还是熬夜的人？' },
  { id: 'q127', category: '习惯、偏好与生活点滴', text: '你的包里通常一定会带的三样东西是什么？' },
  { id: 'q128', category: '习惯、偏好与生活点滴', text: '你最喜欢的咖啡/茶的味道是什么？' },
  { id: 'q129', category: '习惯、偏好与生活点滴', text: '哪种天气最让你感到舒适？' },
  { id: 'q130', category: '习惯、偏好与生活点滴', text: '描述你最糟糕的一次旅行经历。' },
  { id: 'q131', category: '习惯、偏好与生活点滴', text: '你最喜欢哪种艺术形式（绘画、音乐、建筑、文学）？' },
  { id: 'q132', category: '习惯、偏好与生活点滴', text: '你有一个坚持了五年以上的习惯吗？' },
  { id: 'q133', category: '习惯、偏好与生活点滴', text: '如果要在荒岛住一个月，你会带哪三本书？' },
  { id: 'q134', category: '习惯、偏好与生活点滴', text: '你对手机/社交媒体的依赖程度有多高？' },
  { id: 'q135', category: '习惯、偏好与生活点滴', text: '描述你理想中的房子。' },
  { id: 'q136', category: '习惯、偏好与生活点滴', text: '你更喜欢在大城市生活还是在乡间？' },
  { id: 'q137', category: '习惯、偏好与生活点滴', text: '你最喜欢的动物是什么？' },
  { id: 'q138', category: '习惯、偏好与生活点滴', text: '哪种气味会让你瞬间回忆起过去？' },
  { id: 'q139', category: '习惯、偏好与生活点滴', text: '你穿衣打扮的风格在这些年里有什么变化？' },
  { id: 'q140', category: '习惯、偏好与生活点滴', text: '你在金钱上最大的“挥霍”是什么？' },
  { id: 'q141', category: '习惯、偏好与生活点滴', text: '你是一个有条理的人，还是随性的人？' },
  { id: 'q142', category: '习惯、偏好与生活点滴', text: '你的手机屏保是什么？' },
  { id: 'q143', category: '习惯、偏好与生活点滴', text: '哪道菜是你最擅长的？' },
  { id: 'q144', category: '习惯、偏好与生活点滴', text: '你最喜欢的电影台词是什么？' },
  { id: 'q145', category: '习惯、偏好与生活点滴', text: '你平时如何解压？' },
  { id: 'q146', category: '习惯、偏好与生活点滴', text: '你收集过什么东西吗？' },
  { id: 'q147', category: '习惯、偏好与生活点滴', text: '你最喜欢的运动或锻炼方式。' },
  { id: 'q148', category: '习惯、偏好与生活点滴', text: '你是一个购物狂还是极简主义者？' },
  { id: 'q149', category: '习惯、偏好与生活点滴', text: '哪种植物最能代表你的个性？' },
  { id: 'q150', category: '习惯、偏好与生活点滴', text: '描述你最难忘的一次生日。' },

  // ⚪ 第七部分：转折点与抉择
  { id: 'q151', category: '转折点与抉择', text: '你做过的最艰难的决定是什么？' },
  { id: 'q152', category: '转折点与抉择', text: '描述一次你“不听老人言”而导致的后果。' },
  { id: 'q153', category: '转折点与抉择', text: '哪次失败最终变成了你的财富？' },
  { id: 'q154', category: '转折点与抉择', text: '如果当年你没有选择现在的城市，你会在哪里？' },
  { id: 'q155', category: '转折点与抉择', text: '哪次偶然的相遇改变了你的命运？' },
  { id: 'q156', category: '转折点与抉择', text: '你是否曾经历过严重的健康危机？' },
  { id: 'q157', category: '转折点与抉择', text: '描述一次你不得不面对恐惧的经历。' },
  { id: 'q158', category: '转折点与抉择', text: '哪个人曾让你对人性感到失望？' },
  { id: 'q159', category: '转折点与抉择', text: '哪个人曾让你对人性感到希望？' },
  { id: 'q160', category: '转折点与抉择', text: '描述一次你必须做出道德抉择的时刻。' },
  { id: 'q161', category: '转折点与抉择', text: '你最自豪的一次反击或逆袭。' },
  { id: 'q162', category: '转折点与抉择', text: '哪次搬迁或换环境对你的影响最大？' },
  { id: 'q163', category: '转折点与抉择', text: '你是否曾经经历过财务危机？' },
  { id: 'q164', category: '转折点与抉择', text: '哪一刻你觉得自己真正长大了？' },
  { id: 'q165', category: '转折点与抉择', text: '描述一次你对生活失去信心的时刻，后来你是如何走出来的？' },
  { id: 'q166', category: '转折点与抉择', text: '你曾因为别人的建议而后悔过吗？' },
  { id: 'q167', category: '转折点与抉择', text: '哪次偶然的行为让你感到意外的收获？' },
  { id: 'q168', category: '转折点与抉择', text: '你如何定义“好运”？' },
  { id: 'q169', category: '转折点与抉择', text: '描述一次你不得不承认自己错了的时刻。' },
  { id: 'q170', category: '转折点与抉择', text: '哪件事让你对现在的世界格局产生了思考？' },
  { id: 'q171', category: '转折点与抉择', text: '你是否经历过信仰的崩塌或建立？' },
  { id: 'q172', category: '转折点与抉择', text: '描述一次你对抗权威的经历。' },
  { id: 'q173', category: '转折点与抉择', text: '哪种牺牲是你现在回想起来觉得不值得的？' },
  { id: 'q174', category: '转折点与抉择', text: '如果人生可以重启，你会保留哪段经历？' },
  { id: 'q175', category: '转折点与抉择', text: '你觉得自己目前最幸运的事情是什么？' },

  // 🟤 第八部分：反思、展望与遗憾
  { id: 'q176', category: '反思、展望与遗憾', text: '你目前最大的心愿是什么？' },
  { id: 'q177', category: '反思、展望与遗憾', text: '还有什么是你想学但一直没开始的？' },
  { id: 'q178', category: '反思、展望与遗憾', text: '如果你能给20岁的自己一个建议，那会是什么？' },
  { id: 'q179', category: '反思、展望与遗憾', text: '你最希望别人在你葬礼上如何评价你？' },
  { id: 'q180', category: '反思、展望与遗憾', text: '描述一个你尚未实现的梦想。' },
  { id: 'q181', category: '反思、展望与遗憾', text: '你最遗憾没有对谁说出那声“对不起”？' },
  { id: 'q182', category: '反思、展望与遗憾', text: '谁是你生命中那个“错过的遗憾”？' },
  { id: 'q183', category: '反思、展望与遗憾', text: '如果生命只剩下一年，你会如何安排？' },
  { id: 'q184', category: '反思、展望与遗憾', text: '你希望你的孩子从你身上学到什么？' },
  { id: 'q185', category: '反思、展望与遗憾', text: '你觉得自己这辈子最大的成就是什么？' },
  { id: 'q186', category: '反思、展望与遗憾', text: '如果能和世界上任何一个人共进晚餐，你会选谁？' },
  { id: 'q187', category: '反思、展望与遗憾', text: '你最想去但还没去的国家是哪里？' },
  { id: 'q188', category: '反思、展望与遗憾', text: '你觉得自己对社会做出了什么贡献吗？' },
  { id: 'q189', category: '反思、展望与遗憾', text: '描述你心目中“完美的一天”。' },
  { id: 'q190', category: '反思、展望与遗憾', text: '你最害怕被世界遗忘吗？' },
  { id: 'q191', category: '反思、展望与遗憾', text: '你对自己外貌的哪一点最满意？' },
  { id: 'q192', category: '反思、展望与遗憾', text: '如果你能设计自己的墓志铭，会写什么？' },
  { id: 'q193', category: '反思、展望与遗憾', text: '你觉得自己的一生中，爱更多还是被爱更多？' },
  { id: 'q194', category: '反思、展望与遗憾', text: '你最想对世界说的一句话。' },
  { id: 'q195', category: '反思、展望与遗憾', text: '你对未来的科技发展（如AI）感到兴奋还是担忧？' },
  { id: 'q196', category: '反思、展望与遗憾', text: '你理想的老年生活是什么样的？' },
  { id: 'q197', category: '反思、展望与遗憾', text: '描述一个你觉得自己最有生命力的瞬间。' },
  { id: 'q198', category: '反思、展望与遗憾', text: '哪件事让你觉得这辈子活得值了？' },
  { id: 'q199', category: '反思、展望与遗憾', text: '如果有平行时空，你觉得那个时空的你在做什么？' },
  { id: 'q200', category: '反思、展望与遗憾', text: '回顾这200个问题，哪一个让你思考最久？' },
];

export const ORDERS: Order[] = [
  {
    id: 'ORD-2024-001',
    bookTitle: '我的一生故事',
    bookSubtitle: 'Nick 著',
    bookAuthor: 'Nick',
    coverColor: '#e8dcdc',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtPW8FRM5OO0_uXCSzPqNVuxJjMzs6PYU3CARbtjBU_R54BK0gh_b5gsOmaM5XK2Nfq2J8UFcoZfFNqSvLLYJWiTBxHzmVAo695mUmo37LdGBc1bbc-3me5oSJS-dLyBjktkom00esJdfx4eQzSr5fqODQr5eRmAbkY-eDtFfV5topMuqf48m7bHlzW2rkQsHl2ObjS4XcNrMaouB8JZPkQXfwxzA4VeGE74Fse25HIcMovX2PkfTpU7d4TCUZTYLqq0R-uK8w4YY',
    status: 'shipped',
    date: '2024-05-15',
    price: '¥888.00',
    isExample: true,
    trackingNumber: 'SF1425364758',
    logistics: [
      { time: '2024-05-17 10:30', description: '快件已到达 [上海分拨中心]' },
      { time: '2024-05-16 15:20', description: '快件已从 [杭州集散点] 发出' },
      { time: '2024-05-15 18:00', description: '包裹已打包，等待揽收' },
    ]
  }
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Nick 的个人回忆录',
    description: '记录 Nick 先生从童年到现在的珍贵回忆。',
    ownerId: 'u1',
    createdAt: '2024-01-10',
    members: [
      { id: 'u1', name: 'Nick', initials: 'N', projectRole: 'owner', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAoj1aF9YNUvz71eug9j-tRnbAxBMbmSZbWWGkYpbX8ON6whks2yL7UNki8660qWcAthkRVd7FLgYcHBEnOhyAy3NM-VXD94YL2eAHa8HHZik_yXxMtCOnrxeu6X-ANvfXECUe1w5EjP3VfobpEsKaIRxtYBs2OEorBfaoPiZWSZHzTKp_LixD62Q44j3T9on2Mka5gpQ5h5uxDbReG5E7vl9l8x8lTEYG2AAl-0F8sQ6ZeSw8bU9x3HhXKs9oCRPNo9bPYR9HoRY' },
      { id: 'f1', name: 'AT', initials: 'AT', projectRole: 'collaborator', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAWvBEyuKqjC051BXezbxuuLBhWMN23TjQgvsCTWF855vxkHlQ82GMd9i3v-Ht5PzBocYc9FFhZpyW1g4JuhJzapd6UXyV-y4lvITpw6GCIlI1lj8mx1_NmUquVBfFz4Lw8_F3kEe8Lu2ZXq-vkZtNBUlWWNo8CSeK3Fvm_EaF9Ne4adc19tRlK3XBZXcZng40Lu0fbsEuM5AlxNHEYJgTTdQG36PgW4uzruGRSS2Z4rHzCbctU9-mge4fVy79CtcJyk7mmb0o0V8' },
      { id: 'f2', name: 'AM', initials: 'AM', projectRole: 'storyteller' },
    ]
  },
  {
    id: 'p2',
    name: '陈爷爷的家族史',
    description: '陈氏家族的百年传承与奋斗史。',
    ownerId: 'u1',
    createdAt: '2023-11-20',
    members: [
      { id: 'u2', name: '陈爷爷', initials: 'C', projectRole: 'collaborator' },
      { id: 'u1', name: 'Nick', initials: 'N', projectRole: 'owner', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAoj1aF9YNUvz71eug9j-tRnbAxBMbmSZbWWGkYpbX8ON6whks2yL7UNki8660qWcAthkRVd7FLgYcHBEnOhyAy3NM-VXD94YL2eAHa8HHZik_yXxMtCOnrxeu6X-ANvfXECUe1w5EjP3VfobpEsKaIRxtYBs2OEorBfaoPiZWSZHzTKp_LixD62Q44j3T9on2Mka5gpQ5h5uxDbReG5E7vl9l8x8lTEYG2AAl-0F8sQ6ZeSw8bU9x3HhXKs9oCRPNo9bPYR9HoRY' },
    ]
  }
];
